### PR TITLE
uncomment integration test

### PR DESCRIPTION
**Pull request by Onyinye91-ctrl**
I worked on issue #246 (Uncomment integration test on line 66)

### CODE REVIEW

**Review by utam0k — CHANGES_REQUESTED** [review]
@Onyinye91-ctrl Thanks for your first contribution! Did `process_oom_score_adj/process_oom_scocre_ajd.t` pass on your machine? This is how it failed on my machine.
```
$ cat process_oom_score_adj/process_oom_score_adj.t.log | grep "not ok"
not ok 279 - has expected OOM score adjustment
```

**Comment by utam0k** [comment]
@Onyinye91-ctrl Sorry for the lack of explanation, the purpose of that issue is to uncomment and the test will pass. Uncommenting is the final result.

**Comment by yihuaf** [comment]
@utam0k Apparently Github Action passed the test. However, the test fails for me on my local box as well. Maybe this is not as straight forward as we initially thought.

**Comment by utam0k** [comment]
@yihuaf Let's just see if it works with runc.

**Comment by yihuaf** [comment]
> @yihuaf Let's just see if it works with runc.

`runc` passes on my box, so the issue is likely with Youki. I will have to dig a bit deeper.

**Comment by yihuaf** [comment]
@utam0k Now I am really confused. I know why it is not passing on the local box. There are actually two `oom_score_adj` definition, one inside `linux.resource.oom_score_adj`. The other one inside `spec.process.oom_score_adj`. The integration test on the local box sets the `process.oom_score_adj`, but not the `linux.resource.oom_score_adj`. The code only look for `linux.resource.oom_score_adj` and sets it, so of course the test fails.

Now it begs the question, how on earth does it pass on Github Action.......

**Comment by utam0k** [comment]
Sorry, this issue was resolved by following PR.
https://github.com/containers/youki/pull/251/files

**Pull request closed without merging**
