### PR TITLE
use a command instead of label to run benchmark.

### PR DESCRIPTION
**Pull request by utam0k**

### CODE REVIEW

**Comment by utam0k** [comment]
\easy-benchmark

**Comment by utam0k** [comment]
\easy-benchmark

**Comment by utam0k** [comment]
\easy-benchmark

**Comment by utam0k** [comment]
\easy-benchmark

**Comment by utam0k** [comment]
!github easy-benchmark

**Comment by tommady** [comment]
or can we just use a manual trigger like this?
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by utam0k** [comment]
> or can we just use a manual trigger like this? https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

That's a good idea but I think it is better if there is a history by comments or else.

**Comment by utam0k** [comment]
!github easy-benchmark

**Comment by utam0k** [comment]
!github easy-benchmark

**Comment by utam0k** [comment]
I found out it seems the `issue_comment` trigger doesn't activate before merging. I tried to merge it into the main branch in my forked repository and tried it, and it worked.
comment
https://github.com/utam0k/youki/pull/10#issuecomment-974739328
and work
https://github.com/utam0k/youki/runs/4276125789?check_suite_focus=true

**Comment by utam0k** [comment]
@tommady Can I ask you to review it?

**Review by tommady — APPROVED** [review]
so to trigger this action right now becomes to
1. it is a PR
2. with a comment !github easy-benchmark

**Pull request merged**
