### PR TITLE
WIP: Feature seccomp

### PR DESCRIPTION
**Pull request by JonathanBerhe**
@utam0k Hi.
A couple of things are still missing:
1. The definition of the system calls allowed for each architecture in the form of a collection of strings
2. Integrate the filter definition when starting the container process.
Something like [this](https://github.com/opencontainers/runc/blob/654f3319762c896e1f0b23eef0d2cd70fdd6b9b1/libcontainer/standard_init_linux.go#L161)
3. Add tests
4. Try to better define the constants, files and seccomp folder if possible

I would love to receive a hand from you, the topic is not too simple. Feel free to look on the points I have marked and others as well if you feel appropriate and / or necessary.

### CODE REVIEW

**Comment by utam0k** [comment]
@JonathanBerhe Can I ask you to write down the remaining work you have to do?
I'll help you if you have any problems, what can I do for you? (e.g. you don't have time...)

**Comment by yihuaf** [comment]
@utam0k We need someone to continue this right? I can help to continue this.

**Comment by utam0k** [comment]
That's right. And this feature is about to become the last important piece for youki. I'm sorry, but @JonathanBerhe looks busy, so I'm taking him off this issue.

**Comment by utam0k** [comment]
@yihuaf I'd like to you assign this issue. What do you think? You can take over this PR or you can rewrite it from scratch.

**Comment by yihuaf** [comment]
@utam0k sounds good. This may take a bit time since I have to read up on seccomp.

**Comment by yihuaf** [comment]
close in favor of #292 . I choose to use libseccomp to do the heavy lifting, instead directly to prctl.

**Pull request closed without merging**
