### PR TITLE
Specify the protobuf crate because of the rust-criu crate

### PR DESCRIPTION
**Pull request by utam0k**
Workaround: https://github.com/checkpoint-restore/rust-criu/issues/19

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey @utam0k is there anything urgent blocking on this? I think this dependency bug should be handled in upstream itself, rather than we adding the constraint here. I'll approve this PR in case something urgently needs this patch in youki, but otherwise I think we should wait for the crate itself to fix it properly.

**Review by YJDoc2 — APPROVED** [review]

**Comment by utam0k** [comment]
> Hey @utam0k is there anything urgent blocking on this? I

Thanks for your review. We can't build youki from scratch at lease in my environment 😭

**Comment by Mossaka** [comment]
hey there, I would like to understand more about this situation, as `runwasi` depends on both `youki` and `containerd-shim`, which in turn depend on `protobuf`. I would not like to see a transititive dependency version conflict if both crates specify a **exact version** for protobuf.

If you have encountered a breaking change in the latest version `protobuf`, I'd suggest not to use exact version pinning, but more relexed measure like this one: https://github.com/containerd/rust-extensions/pull/322

**Comment by utam0k** [comment]
> hey there, I would like to understand more about this situation, as `runwasi` depends on both `youki` and `containerd-shim`, which in turn depend on `protobuf`. I would not like to see a transititive dependency version conflict if both crates specify a **exact version** for protobuf.
> 
> If you have encountered a breaking change in the latest version `protobuf`, I'd suggest not to use exact version pinning, but more relexed measure like this one: [containerd/rust-extensions#322](https://github.com/containerd/rust-extensions/pull/322)

Hi, @Mossaka. As far as my memory, it caused flaky CI as the comment on https://github.com/checkpoint-restore/rust-criu/issues/19.  How about specifying the bottom version of `protobuf` crate in youki?

> This is fatal as this WILL [bring build errors](https://github.com/terrapkg/packages/actions/runs/6691482351/job/18178806142#step:7:3271) on anything that depends on your crate once a newer version of protobuf is available.

**Comment by Mossaka** [comment]
What does bottom version mean?

**Comment by utam0k** [comment]
> What does bottom version mean?

It means the range for the crate's version. Like `^0.3.2`. Is it enough for runwasi?

**Comment by utam0k** [comment]
Or it may now be stable. Let me see for a while if the CI would be unstable.

**Comment by Mossaka** [comment]
Yeah, runwasi resolved this issue by updating containerd-shim-protos to the latest version, which I made the change to relex the version requirement for `protobuf`. `^0.3.2` is better than `=0.3.2` but still not great.

**Pull request merged**
