### PR TITLE
Use saturating_sub instead of - for unsigned ints

### PR DESCRIPTION
**Pull request by rumpl**
This fixes a panic if the operation with the unsigned ints would result in a negative number

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey @rumpl  , the formatting check is failing in the CI. Can you run cargo fmt, and push again. Also if possible, can you amend the current commit instead of adding a new one for formatting.

I am also curious if we should do a similar saturating operation for other additions or subtractions related to such cgroups values. What do you think?

**Comment by rumpl** [comment]
Hey, I created a new PR that only fixes formatting, the failures are unrelated to the changes I made here, the PR: #1532

**Comment by rumpl** [comment]
> I am also curious if we should do a similar saturating operation for other additions or subtractions related to such cgroups values. What do you think?

I looked briefly but didn't see any other code where there are subtractions with unsigned ints

**Comment by utam0k** [comment]
@rumpl May I ask you to rebase from the latest main branch?

**Review by utam0k — APPROVED** [review]

**Comment by rumpl** [comment]
@utam0k done :+1:

**Review by YJDoc2 — APPROVED** [review]
lgtm :+1:

**Comment by YJDoc2** [comment]
Thanks a lot!

**Pull request merged**
