### PR TITLE
Prepare for v0.4.0

### PR DESCRIPTION
**Pull request by utam0k**
ref: https://github.com/containers/youki/issues/2879

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey, I think this release should bump the minor number, so 0.4.0 , specially because of https://github.com/containers/youki/pull/2818 , which is a breaking change. wdyt?

**Comment by utam0k** [comment]
> Hey, I think this release should bump the minor number, so 0.4.0 , specially because of #2818 , which is a breaking change. wdyt?

Make sense!

**Comment by YJDoc2** [comment]
Hey the fille changes still show the version diff as `0.3.4` , we need to update that right? Also will the tagpr PR (https://github.com/containers/youki/pull/2791) for changelog get auto-updated to the `0.4.0` instead of `0.3.4` once we merge this, or we might need to update it manually?

**Comment by YJDoc2** [comment]
ok, so tagpr pr is updated to correct 0.4.0, and it also has the updation of `.tagpr` that is here, so what changes does this pr exactly needs? Or we can merge the tagpr for the release?

**Comment by yihuaf** [comment]
I think we can close this in favor of #2791

**Comment by utam0k** [comment]
> Hey the fille changes still show the version diff as `0.3.4` , we need to update that right? Also will the tagpr PR (#2791) for changelog get auto-updated to the `0.4.0` instead of `0.3.4` once we merge this, or we might need to update it manually?

I forgot `git add .` 🤦

**Comment by utam0k** [comment]
> ok, so tagpr pr is updated to correct 0.4.0, and it also has the updation of `.tagpr` that is here, so what changes does this pr exactly needs? Or we can merge the tagpr for the release?

Merging #2791 after merging this PR should complete the release. Sorry for the confusion. The release flow is slightly broken. We hope to have it in place before the next release. Normally, the changes in this PR should be included in #2791, but that is not the case right now.

**Review by YJDoc2 — APPROVED** [review]
:tada:

**Comment by YJDoc2** [comment]
> Merging https://github.com/containers/youki/pull/2791 after merging this PR should complete the release.

ok, got it :+1: I have approved the PR, you can go ahead once the CI is done

**Comment by YJDoc2** [comment]
@utam0k , I have approved the release env workflows, so v0.4.0 should get released and uploaded to crates.io

**Comment by utam0k** [comment]
> @utam0k , I have approved the release env workflows, so v0.4.0 should get released and uploaded to crates.io

All of this has already automated.

**Pull request merged**
