### PR TITLE
Automatically publish packages

### PR DESCRIPTION
**Pull request by MostlyAmiable**
I [just published](https://github.com/checkpoint-restore/rust-criu/pull/7) `rust-criu`, which I believe was the last blocker to getting youki's packages published. I added an additional job to the release action so that new versions will get published automatically, just need to add a token to the repo secrets under `CARGO_REGISTRY_TOKEN`. I used `--no-verify` because it's already verified as part of the `check` job, and I removed the `documentation` attribute from the manifests because they [default to docs.rs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field).

Ref: https://github.com/containers/youki/issues/586

<a href="https://gitpod.io/#https://github.com/containers/youki/pull/1000"></a>

### CODE REVIEW

**Comment by utam0k** [comment]
@MostlyAmiable Thanks for your PR.  You got a lucky number #1000. It seems òci-spec-rs` is failed because the maintainer(it's me) doesn't release a new version 😭 
I'll deal with the oci-spec-rs part later, so could you please remove that part from this PR? Of course you can do it.

**Review by utam0k — APPROVED** [review]
Thanks!

**Comment by utam0k** [comment]
@MostlyAmiable There are still several oci-spec-rs that are version-specific.

**Comment by MostlyAmiable** [comment]
@utam0k Woops, sorry for the oversight and the delayed response. Does it make sense to wait to merge these changes until we can depend on a published version of `oci-spec-rs`, since otherwise we still can't publish these crates as long as they have git dependencies?

**Comment by utam0k** [comment]
@MostlyAmiable Please wait for merging this PR
https://github.com/containers/oci-spec-rs/pull/108

**Comment by utam0k** [comment]
@MostlyAmiable Can I ask you to pass the CIs?
```console
$ git commit --amend --no-edit -s
```

**Comment by MostlyAmiable** [comment]
Is the intent of the DCO signoff not implied by the fact that I'm contributing code under the Apache 2.0 license?

**Comment by MostlyAmiable** [comment]
Feel free to merge after approving/passing workflows, it's a race between me and dependabot bumping dependency versions 😅

**Comment by utam0k** [comment]
> Is the intent of the DCO signoff not implied by the fact that I'm contributing code under the Apache 2.0 license?

This is a process just in case. Thanks for your cooperation.

**Comment by utam0k** [comment]
@MostlyAmiable Thanks! 💯

**Pull request merged**
