### PR TITLE
Bump wasmer version to 3.0.1

### LINKED ISSUE #1372: Upgrade wasmer to v3.0

### PR DESCRIPTION
**Pull request by chermehdi**
Fixes #1372

<a href="https://gitpod.io/#https://github.com/containers/youki/pull/1375"></a>

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey @chermehdi Are you still working on this? If there are any issues or you need any help, feel free to ask :+1:

**Comment by chermehdi** [comment]
@YJDoc2  It seems that I am not able to build after the update, as `cargo check --all-features` fails specifically `cargo check --features wasmer-wasi` I couldn't figure out what's the issue

**Comment by YJDoc2** [comment]
@chermehdi Apologies for the late reply. Can you show me the errors? Also, can you try rebase this PR on current master and fix conflicts? That might possibly solve the errors.

**Comment by yihuaf** [comment]
close in favor of #1825

**Pull request closed without merging**
