### PR TITLE
Add integration tests into code coverage generation

### PR DESCRIPTION
**Pull request by YJDoc2**
This extends on #898 , and adds a commit after the commits in that PR.
That one should be first taken into consideration before this one.

This adds OCI integration tests when running tests to generate coverage info.
Based on https://github.com/containers/youki/issues/316#issuecomment-1119924328

<a href="https://gitpod.io/#https://github.com/containers/youki/pull/899"></a>

### CODE REVIEW

**Comment by utam0k** [comment]
@YJDoc2 Thanks! How can I know that this pr works fine?

**Comment by YJDoc2** [comment]
Hey @utam0k , I am not sure what you mean...
If you mean by code's perspective , this does not change any code except removing the feature flag, done by taiki-e in #898, which should be reviewed first.
If you mean if the CI works, then the updated steps are followed from the comment in the issue, and you can see the stats at https://app.codecov.io/gh/containers/youki/compare/899

**Comment by utam0k** [comment]
@YJDoc2 Sorry, please let me explain again. I wonder why the code coverage goes down by this PR?

**Comment by YJDoc2** [comment]
Hey @utam0k , I tried checking why the coverage is dropping, but could not find any specific reason. As the main branch has recent commits, the codecov is not showing the diff (at their website) anymore. 

So, I am closing this PR for now, I will try to investigate further and open another PR if I could find a way to add integration tests into coverage checks.

Sorry for the delay in response :sweat:

**Pull request closed without merging**
