### PR TITLE
 Introduce a workspace to enable execution of commands in bulk.

### PR DESCRIPTION
**Pull request by utam0k**

### CODE REVIEW

**Review by YJDoc2 — COMMENTED** [review]
lgtm :+1:
I think as workspace makes the /target dir common for both (youki and cgroups), so we might be able to remove the separate cache action for cgroups as well, will have to check that.

In cgroups I think you were trying to extract common statement outside if-else, but it might create issues for #266 ? It is already having issues with merge conflicts with existing files, so I feel it'd be better to leave those changes for @guni1192 to add in their PR. What do you think?

**Comment by Furisto** [comment]
You can leave it out. My open PR contains the same change, so it will not get lost.

**Comment by Furisto** [comment]
Oh wait, I don't think this will work, because with the workspace clippy will flag the code now.

**Comment by utam0k** [comment]
@Furisto @YJDoc2 
Thank you for your comments. Well, I don't want to bother @guni1192  too much since https://github.com/containers/youki/pull/266 is a big change, so I'll draft this PR and wait for it to be merged.

**Comment by utam0k** [comment]
@Furisto @YJDoc2 PTAL

**Comment by YJDoc2** [comment]
Additionally we can remove the Cargo.lock fine in cgroups, and combine the separate cache actions, as the compiled cgroups files are kept in the youki's target/ only.

https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
>A workspace is a set of packages that share the same Cargo.lock and output directory.

Other than that lgtm :+1:

**Comment by utam0k** [comment]
> Additionally we can remove the Cargo.lock file in cgroups, and combine the separate cache actions, as the compiled cgroups files are kept in the youki's target/ only.
> 
> https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html
> 
> > A workspace is a set of packages that share the same Cargo.lock and output directory.
> 
> Other than that lgtm

@YJDoc2 Oh thanks for the review. I've taken care of it.

**Review by YJDoc2 — APPROVED** [review]
lgtm :+1: if you want to keep cache actions separate for now.

**Comment by utam0k** [comment]
> lgtm  if you want to keep cache actions separate for now.

We could certainly organize it. I'll consider it in another PR.

**Pull request merged**
