### PR TITLE
bump clap and use crate_version macro

### PR DESCRIPTION
**Pull request by humancalico**
There is also a [crate_authors](https://docs.rs/clap/3.0.0-beta.4/clap/macro.crate_authors.html) macro that can be used in a similar way

### CODE REVIEW

**Comment by Furisto** [comment]
@humancalico Looks good, but you need to run cargo fmt

**Comment by utam0k** [comment]
@humancalico hmm. There was some kind of suspicious log on the CI and it was taking quite a while to test. I'd like to confirm, did the test passed on your machine?

**Comment by humancalico** [comment]
@utam0k the tests are kinda flaky. On three different runs I got different results each time and different tests failing

**Comment by utam0k** [comment]
I create the PR to fix the unstable tests. 
https://github.com/containers/youki/pull/267
However, I have a feeling that this error of ci at this PR is something different.

**Comment by humancalico** [comment]
The `test_run_hook` function is failing for me right now
```
running 29 tests
test container::state::tests::test_create_status ... ok
test container::container::tests::test_set_id ... ok
test container::container::tests::test_basic_getter ... ok
test container::state::tests::test_creating_status ... ok
test container::state::tests::test_running_status ... ok
test capabilities::tests::test_reset_effective ... ok
test container::state::tests::test_paused_status ... ok
test container::state::tests::test_stopped_status ... ok
test hooks::test::test_run_hook_timeout ... ignored
test namespaces::tests::test_apply_namespaces ... ok
test hooks::test::test_run_hook ... FAILED
test process::init::tests::test_cleanup_file_descriptors ... ok
test process::init::tests::test_get_open_fds ... ok
test signal::tests::test_conversion_from_string_should_be_failed ... ok
test process::channel::tests::test_channel_id_mapping_ack ... ok
test signal::tests::test_conversion_from_string ... ok
test utils::tests::test_get_cgroup_path ... ok
test utils::tests::test_join_absolute_path ... ok
test utils::tests::test_join_absolute_path_error ... ok
test utils::tests::test_parse_env ... ok
test process::channel::tests::test_channel_init_graceful_exit ... ok
test process::channel::tests::test_channel_init_ready ... ok
test process::channel::tests::test_channel_intermadiate_ready ... ok
test process::channel::tests::test_channel_intermedaite_graceful_exit ... ok
error: test failed, to rerun pass '--lib'
h
```

**Comment by Furisto** [comment]
@humancalico We have some problems with code coverage right now, so we have disabled it until further investigation. Please rebase and try again.

**Comment by humancalico** [comment]
@Furisto still getting the same failure

**Review by Furisto — APPROVED** [review]

**Comment by Furisto** [comment]
lgtm

**Pull request merged**
