### PR TITLE
CI Code Coverage Fix

### PR DESCRIPTION
**Pull request by YJDoc2**
ref #226 #272 
This attempts to Fix code coverage issue :
After seeing https://github.com/actions-rs/grcov/issues/105, which asks to update code coverage using inbuilt features of llvm, as well as PyO3 also seems to use it, (which is quite a big lib). So I tried to use similar workflow as https://github.com/PyO3/pyo3/blob/main/.github/workflows/ci.yml to see if it can fix the issue.

### CODE REVIEW

**Comment by YJDoc2** [comment]
So I think this does work for accounting code coverage in cgroups as well. On codecov docs, it states that reports are merged : https://docs.codecov.com/docs/merging-reports So I think this merges the code coverage for youki as well as cgroups both.

On another node, this didn't spawn format and clippy jobs as no code was changed, which means the check job is working as expected !!! :tada: :tada: :tada: 

@utam0k please take a look once, and verify.

**Comment by YJDoc2** [comment]
I also think the grcov.yaml file is not needed anymore and can be deleted, but not sure.

**Comment by YJDoc2** [comment]
Also, I just came around https://github.com/Swatinem/rust-cache, should we try changing our plain cache action with this one specifically for rust?

**Review by Furisto — APPROVED** [review]

**Comment by utam0k** [comment]
Let's install it and measure the benchmarks!
> Also, I just came around https://github.com/Swatinem/rust-cache, should we try changing our plain cache action with this one specifically for rust?

**Review by utam0k — APPROVED** [review]

**Pull request merged**
