### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by utam0k**

### CODE REVIEW

**Review by Furisto — APPROVED** [review]

**Comment by YJDoc2** [comment]
Hey, do you want me to update the `MirgationGuide.md` file for this? Or is it fine to leave it as it is for now?

**Comment by utam0k** [comment]
@YJDoc2 I forgot about it 🤦‍♂May I ask you to do it? But it is not rushing because we can update it after releasing v0.2.0
> Changes that will occur for properly running in rootless mode : TODO (@YJDoc2)

**Comment by YJDoc2** [comment]
> @YJDoc2 I forgot about it 🤦‍♂May I ask you to do it? But it is not rushing because we can update it after releasing v0.2.0

I'll open a PR in few minutes, it is not a big change.

**Comment by YJDoc2** [comment]
@utam0k https://github.com/containers/youki/pull/2334 :eyes: 

Also I think for this PR (releasing 0.2.0) `feature` label would be more appropriate than cleanup.

**Pull request merged**
