### PR TITLE
Check youki is started in user namespace

### PR DESCRIPTION
**Pull request by Furisto**

### CODE REVIEW

**Comment by utam0k** [comment]
@YJDoc2 for :eyes:

**Comment by yihuaf** [comment]
Is there a context to this PR. Is this intended to use in the integration test?

**Comment by YJDoc2** [comment]
@yihuaf This was a starting point for the fix of running youki without sudo via podman (https://github.com/containers/youki/pull/1171) . I'm working on it, and figuring out the solution ; this one is just parked for reference.

**Comment by YJDoc2** [comment]
Done via #2370 :tada: Thanks for helping with the initial approach!

**Comment by utam0k** [comment]
@YJDoc2 
Thanks for your hard work!

**Pull request closed without merging**
