### PR TITLE
style: adjusting the position of parameters and flag declarations

### PR DESCRIPTION
**Pull request by unknowndevQwQ**
Split from #465
Because this pr does not have much to do with #465

### CODE REVIEW

**Comment by utam0k** [comment]
@unknowndevQwQ Why we need this change?

**Comment by unknowndevQwQ** [comment]
> @unknowndevQwQ Why we need this change?

It will become a little more organized

**Comment by utam0k** [comment]
> > @unknowndevQwQ Why we need this change?
> 
> It will become a little more organized
> 
> When trying to add the --debug flag, I didn't even realize where the --root flag was declared

I don't understand what changes of this PR improve. Would you please explain it to me?

**Comment by unknowndevQwQ** [comment]
> > > @unknowndevQwQ Why we need this change?
> > 
> > 
> > It will become a little more organized
> > When trying to add the --debug flag, I didn't even realize where the --root flag was declared
> 
> I don't understand what changes of this PR improve. Would you please explain it to me?

The ordering of the parameter names in a-z order facilitates a quicker and more accurate search for the relevant content of a parameter when there are quite a few of them.

**Review by utam0k — APPROVED** [review]

**Pull request merged**
