### PR TITLE
Cargo.toml: remove unused dependnecies

### PR DESCRIPTION
**Pull request by Mossaka**
remove unused deps in youki, found by running `cargo machete` 

question: perhaps we should consider adding [this](https://github.com/bnjbvr/cargo-machete?tab=readme-ov-file#cargo-machete-action) to the CI?

### CODE REVIEW

**Review by jprendes — APPROVED** [review]
LGTM

**Comment by utam0k** [comment]
> question: perhaps we should consider adding [this](https://github.com/bnjbvr/cargo-machete?tab=readme-ov-file#cargo-machete-action) to the CI?

I didn't know that. Exactly. Do you have an intention to contribute?

**Comment by Mossaka** [comment]
@utam0k I just realized that my PR removed a pinned version of `protobuf`. Can you evaluate if that's needed? https://github.com/containers/youki/pull/2921/files#diff-05eb4a3f83693cfbdc185e744c79b31a56b710583017eb128a83fc9dfaf64561L51

**Comment by utam0k** [comment]
@Mossaka I've left my comment on here.
https://github.com/containers/youki/pull/2497#issuecomment-2395709055

**Pull request merged**
