### PR TITLE
Add format check ci

### LINKED ISSUE #125: Add code format check in CI.
cc @utam0k

### PR DESCRIPTION
**Pull request by duduainankai**
Close #125

### CODE REVIEW

**Review by utam0k — APPROVED** [review]
lgtm

**Comment by duduainankai** [comment]
Do you think we should add dependency on these steps ? 

Such like do not run test if fail to check format.

**Comment by utam0k** [comment]
@duduainankai Thanks for your advice. I don't think we need to add the dependencies. Are there any advantages or disadvantages?

**Comment by duduainankai** [comment]
pros: simplify CI pipline procedure, since code format check failed means CI failed and cannot be merged.

cons: test and format check steps cannot run in parallel, and maybe another CI pipline to find test failed.

I think both are acceptable, so just a simple ask, it's up to you.

@utam0k

**Comment by utam0k** [comment]
@duduainankai Thanks for your simplified summary. I understood. This time we will adopt not to create dependencies.

**Pull request merged**
