### PR TITLE
config.vm.box changed to centos/7

### PR DESCRIPTION
**Pull request by minegishirei**
Issue link is https://github.com/containers/youki/issues/2693

changed config.vm.box from fedora/33-cloud-base to centos/7

It seems to worked.

image

image

Please ignore if you don't need it.

### CODE REVIEW

**Comment by YJDoc2** [comment]
Hey, can you 
1. sign your commit, you can see the details in the failed DCO CI
2. change the image to `fedora/39-cloud-base` , instead of switching to centos?  While I don't think there would be anything particularly wrong with centos, I would prefer to keep the original distro that the vagrantfile was created with if possible

Thanks for your contribution!

**Comment by minegishirei** [comment]
It sounds good to keep box image `fedora/39-cloud-base`.
I apologize for the inconvenience.

**Comment by minegishirei** [comment]
For a while, I use below command.
I won't work on it for a while.
Sorry... 

```sh
VAGRANT_VAGRANTFILE=Vagrantfile.containerd2youki vagrant up
```

**Comment by YJDoc2** [comment]
> I won't work on it for a while.
Sorry...

No worries, thank you for noticing and reporting this issue, as well as suggesting a fix! I'll fix the box image in some other PR. Thanks!

**Pull request closed without merging**
