### PR TITLE
New logo!

### PR DESCRIPTION
**Pull request by utam0k**
This will give the Containers top page a uniform taste.
https://github.com/containers

Made by @mairin and Red Hat designer team. Thanks!

### CODE REVIEW

**Comment by utam0k** [comment]
https://github.com/containers/common/pull/1409

**Comment by rumpl** [comment]
Love it!

**Review by saschagrunert — APPROVED** [review]
Whoop!

**Comment by mairin** [comment]
Designed by Jess Chitas :)

**Pull request merged**
