### PR TITLE
convert youki to use tracing

### PR DESCRIPTION
**Pull request by yihuaf**
This PR converts youki to use `tracing` crate for logging. I did the minimal to make the transition, but `tracing` crate allows for much richer logging and instrumentation. This is related to #1348 in that this would be a pre-requirement to implement open-telemetry.

In addition, the reason I decide to do this now because error handling can be difficult without tracing/logging support. In general with error handling, the audience are either the user/operator (human) or for code to handle. It is important to log as much as possible of the context of an error. There are usually 2 choices. Either we store the context of the error into the error itself, or we log the context and keep the error size small. There is no right answer and usually we need a combination of both. `tracing` crate allows us to minimize the context we have to store inside the error itself, and instead opting for rich logging.

Note, I tried to keep the change minimal, but switching logging infrastructure does have a wide impact. Hopefully this is not too disruptive to people.

### CODE REVIEW

**Comment by yihuaf** [comment]
I am able to reproduce this now. First, the old behavior is the same as the new, with the log line being slightly different, but the overall length is similar. In fact, the tracing in this PR produced a shorter line since the file path and line number is not turned on by default. Therefore, I believe this is a separate issue not related to logging or tracing.

To resolve this, it seems that bpftrace is omitting the long lines. I can confirm that my shell window will wrap the line correctly. So bpftrace is cutting off the lines.

**Comment by yihuaf** [comment]
The integration test is failing and I suspect this has to do with the tempfile change. I will investigate.

**Comment by yihuaf** [comment]
> The container runtime does not work with this timescale.

This is a good point.

> bpftrace is probably currently the most usable way to fix bugs in kubernetes. I am not sure how to do it with other ways, because it is too deep in the hierarchy from kubelet, and it is difficult to do.

Oh, this is how you are using `bpftrace`. This makes sense.

**Comment by yihuaf** [comment]
I turned off the timestamp for the text format to stderr. This should produce a shorter log line with log level, log target, and the actual log line. I left the other format unchanged for now. Let me know if you think we should remove timestamp for other cases as well (JSON and logging to file).

> I don't think it would be desirable to make the logs longer simply from the standpoint of readability.

Normally, this is not too much of an issue because we can make a long log line to be more human readable with nice formatting. In fact, the tracing crate has a really nice `pretty` formatter to make the logs more readable. It breaks the long line into multiple lines and adds coloring to the log line.

However, in this specific case, we are using `bpftrace`. From this perspective, the log line is a single `write` syscall with a long line. It will also cut off at 225 ish char due to internal limits. This limits makes sense because `bpftrace` is not designed to read logs. It is designed to capture the syscall trace. In another word, you are hacking `bpftrace` as a log collector for youki, but I can see this is a nice way to debug youki under kubelet. Please correct me if I am misunderstanding you.

In my view, assume debugging is your only concern, the long term solution is to use something more appropriate to view tracing/logging. For example, we can configure the trace/log to write to journald or syslog. Then, by observing syslog or journald or using `journalctl`, we can view the logs from `youki` in a similar way on how you use `bpftrace` right now. Of course, there are other tracing viewers as well but they all work in similar ways. I believe these days, we can even ship the tracing to something like datadog if we really wants.

For now, let's keep it simple and see this the current setup works for us. But, the real super power of tracing is to log as much information as possible along with metrics. It can be pretty powerful beyond just logging and the amount of logs/data entry generated from tracing will become too much for `bpftrace` to handle at some point. We are not there now, but we slowly will.

**Comment by utam0k** [comment]
@yihuaf I agree with you, logging with bpftrace is pretty hacky. It should be turned off. It would be best if it could be turned off in the future, but for now this debugging method is necessary.
However, if OpenTelemetry tracing could be placed anywhere and the sampling rate could be set to 100%, I think it could be turned off.

**Review by utam0k — APPROVED** [review]
Thanks a lot 🙏

**Pull request merged**
