### PR TITLE
[WIP] fix podman on Running conmon under slice step will hang

### LINKED ISSUE #457: Debug issue with podman with limited memory resource
```console
coder@pearl:~/youki$ sudo podman --runtime /home/coder/youki/youki run --rm --memory 1M fedora echo it works
```
will hangup.

OS version:
```
Linux pearl 5.8.0-1041-azure #44~20.04.1-Ubuntu SMP Fri Aug 20 20:41:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

podman version:
```
podman version 3.3.1
```

### PR DESCRIPTION
**Pull request by tommady**
fix #457 

after modifying,
the podman conmon will not hang up to the issue described point.

### CODE REVIEW

**Comment by tommady** [comment]
@Furisto could you guide me on why changed this line of code
```
if args.rootless.is_some()
```
the deletions at libcgroups/src/v1/manager.rs:153 will all show the path of the file does not exist.
or am I making something wrong?

please guide me. 🙇🏻

**Comment by Furisto** [comment]
I assume you are starting podman with sudo? Then if you invert the condition the cgroup configuration will not be applied  and therefore the code that is crashing youki will not be executed. 

I would expect that the problem is that podman is using systemd as cgroup manager by default and therefore the cgroup path will be something like system.slice:podman243sdf:23489sdf which the cgroup v1 manager cannot handle correctly. This will be fixed when systemd support has been finished which is currently ongoing. 

You can try to start podman with --cgroup-manager=cgroupfs, which should prevent the hang.

**Comment by tommady** [comment]
> I assume you are starting podman with sudo? Then if you invert the condition the cgroup configuration will not be applied and therefore the code that is crashing youki will not be executed.
> 
> I would expect that the problem is that podman is using systemd as cgroup manager by default and therefore the cgroup path will be something like system.slice:podman243sdf:23489sdf which the cgroup v1 manager cannot handle correctly. This will be fixed when systemd support has been finished which is currently ongoing.
> 
> You can try to start podman with --cgroup-manager=cgroupfs, which should prevent the hang.

Thank you for your explaination!
I learn a lot.

But unfortunatly I tried the flag you mentioned still not work.

both are the current youki main branch release build:
```bash
sudo podman --runtime /home/tommady/youki --cgroup-manager=systemd run --rm --memory 1M fedora echo hello world
Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
---
in my local device hang a while then response
---
hello world
```

```bash
sudo podman --runtime /home/tommady/youki --cgroup-manager=cgroupfs run --rm --memory 1M fedora echo hello world
Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
---
in my local device same behavior like systemd, hang a while then response
---
hello world
```

Do you have any suggestion of which area that I can dig more?

**Comment by Furisto** [comment]
So it does work eventually, it is just slow? How long does it take until the container gets started? What happens if you set the memory limit to e.g. 12M?

**Comment by tommady** [comment]
> So it does work eventually, it is just slow? How long does it take until the container gets started? What happens if you set the memory limit to e.g. 12M?

ya, if the memory limitation is >= 2M, everything will be fine, smoothly. 🙇🏻

**Comment by Furisto** [comment]
Then 2 megabytes is just the minimum required allotment for the time being.

**Comment by utam0k** [comment]
It may be that youki simply don't have enough memory. 
There are a few things to check.
* While `apply_cgoup()` execute, does the process already have a limit on memory usage?
* Does runc work fine when using memory limit?

**Comment by tommady** [comment]
I am trying to say is the behavior I am wondering about ( please correct me if I am wrong

it looks like some signal has not been sending out or receiving properly, like a golang channel blocking,
from [here](https://github.com/containers/podman/blob/main/libpod/oci_conmon_linux.go#L1448)
goes down into [here](https://github.com/containers/podman/blob/d6ef903164512e6fa7903bb0b85a1852117df37b/utils/utils_supported.go#L60) 
then blocked

and since youki has not been killed like runc by podman, so I guess it is not about the memory limitation.
this is my humble and silly guessing please guide and correct me 🙇🏻 

crun (sudo or not)
```bash
sudo podman --runtime /usr/bin/crun --log-level debug run --rm --memory 1M fedora echo it works

DEBU[0000] /usr/libexec/podman/conmon messages will be logged to syslog
DEBU[0000] running conmon: /usr/libexec/podman/conmon    args="[--api-version 1 -c e952ff552c89a6b07205494b9b13c11e4
e427fe1f465b709e0020ad146c31301 -u e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad146c31301 -r /usr/bin/crun
 -b /var/lib/containers/storage/overlay-containers/e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad146c31301/
userdata -p /var/run/containers/storage/overlay-containers/e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad14
6c31301/userdata/pidfile -n blissful_yonath --exit-dir /var/run/libpod/exits --full-attach -s -l k8s-file:/var/lib/c
ontainers/storage/overlay-containers/e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad146c31301/userdata/ctr.l
og --log-level debug --syslog --conmon-pidfile /var/run/containers/storage/overlay-containers/e952ff552c89a6b0720549
4b9b13c11e4e427fe1f465b709e0020ad146c31301/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --r
oot --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/containe
rs/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-comman
d-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit-com
mand-arg /usr/bin/crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-o
pt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-command-arg jour
nald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --e
xit-command-arg e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad146c31301]"
INFO[0000] Running conmon under slice machine.slice and unitName libpod-conmon-e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad146c31301.scope
---
smoothly going through
---
DEBU[0000] Received: 516178
INFO[0000] Got Conmon PID as 516164
DEBU[0000] Created container e952ff552c89a6b07205494b9b13c11e4e427fe1f465b709e0020ad146c31301 in OCI runtime
```

runc (sudo or not)
```bash
sudo podman --runtime /usr/sbin/runc --log-level debug run --rm --memory 1M fedora echo it works

DEBU[0000] /usr/libexec/podman/conmon messages will be logged to syslog
DEBU[0000] running conmon: /usr/libexec/podman/conmon args="[--api-version 1 -c de7aa3966e7ecd1138292f7723bbfa7bb
d1e90222c85a345f5c345e3aa44b728 -u de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3aa44b728 -r /usr/sbin/run
c -b /var/lib/containers/storage/overlay-containers/de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3aa44b72$
/userdata -p /var/run/containers/storage/overlay-containers/de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3
aa44b728/userdata/pidfile -n loving_meninsky --exit-dir /var/run/libpod/exits --full-attach -s -l k8s-file:/var/lib/
containers/storage/overlay-containers/de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3aa44b728/userdata/ctr.
log --log-level debug --syslog --conmon-pidfile /var/run/containers/storage/overlay-containers/de7aa3966e7ecd1138292
f7723bbfa7bbd1e90222c85a345f5c345e3aa44b728/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --
root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/contain
ers/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-comma
nd-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit-co
mmand-arg /usr/sbin/runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage
-opt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-command-arg jo
urnald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm -
-exit-command-arg de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3aa44b728]"
INFO[0000] Running conmon under slice machine.slice and unitName libpod-conmon-de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3aa44b728.scope
---
no hang, get the result -1 instantly
---
DEBU[0000] Received: -1
DEBU[0000] Cleaning up container de7aa3966e7ecd1138292f7723bbfa7bbd1e90222c85a345f5c345e3aa44b728
...
```

youki (sudo or not)

```bash
sudo podman --runtime /home/tommady/youki --log-level debug run --rm --memory 1M fedora echo it works

DEBU[0000] /usr/libexec/podman/conmon messages will be logged to syslog
DEBU[0000] running conmon: /usr/libexec/podman/conmon    args="[--api-version 1 -c a8ca923d97cfc44ba077c4cc89d53af12
479ba890de7ed9b2d9582a032683c90 -u a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9582a032683c90 -r /home/tommady
/youki -b /var/lib/containers/storage/overlay-containers/a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9582a0326
83c90/userdata -p /var/run/containers/storage/overlay-containers/a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9
582a032683c90/userdata/pidfile -n romantic_buck --exit-dir /var/run/libpod/exits --full-attach -s -l k8s-file:/var/l
ib/containers/storage/overlay-containers/a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9582a032683c90/userdata/c
tr.log --log-level debug --syslog --conmon-pidfile /var/run/containers/storage/overlay-containers/a8ca923d97cfc44ba0
77c4cc89d53af12479ba890de7ed9b2d9582a032683c90/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg
 --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /var/run/cont
ainers/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-co
mmand-arg systemd --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit
-command-arg /home/tommady/youki --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg -
-storage-opt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-comman
d-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-ar
g --rm --exit-command-arg a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9582a032683c90]"
INFO[0000] Running conmon under slice machine.slice and unitName libpod-conmon-a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9582a032683c90.scope
---
on my local device, youki hang a while here, on @chenyukang device he claimed it is hangup entirely
---
DEBU[0004] Received: 516717
INFO[0004] Got Conmon PID as 516703
DEBU[0004] Created container a8ca923d97cfc44ba077c4cc89d53af12479ba890de7ed9b2d9582a032683c90 in OCI runtime
```

**Comment by Furisto** [comment]
I tried to reproduce it, but I cannot observe any hang.

**Comment by tommady** [comment]
close this PR for not really helping to address the issue

**Pull request closed without merging**
