### PR TITLE
Move to 2021

### PR DESCRIPTION
**Pull request by chenyukang**
closing #404

### CODE REVIEW

**Comment by utam0k** [comment]
> Hey I think @utam0k has once previously noted that building with 2021 edition took quite a while, but I have tested with the 1.54.1 today, and both dev and release builds were compiling in reasonable time. So I think we can now migrate to 2021 edition, if there are no other issues. 👍

Is it 1.56.1? It works fine for my local with rustc 1.56.1.

**Comment by YJDoc2** [comment]
Oops, yeah I meant 1.56.1 :sweat_smile: :sweat_smile:

**Comment by utam0k** [comment]
@chenyukang I believe this PR can restart!

**Comment by chenyukang** [comment]
> @chenyukang I believe this PR can restart!

Synced with main, please review it.

**Review by utam0k — APPROVED** [review]
:tada:

**Pull request merged**
