### PR TITLE
:memo: Remove GitPod and add link to GitHub codespaces

### PR DESCRIPTION
**Pull request by homersimpsons**
Fixes https://github.com/containers/youki/issues/2678

### CODE REVIEW

**Comment by YJDoc2** [comment]
Thanks for opening the PR!
May I ask you to sign off your commit : https://github.com/containers/youki/pull/2717/checks?check_run_id=22180998348

**Comment by homersimpsons** [comment]
There are 2 failures:
- https://github.com/containers/youki/actions/runs/8115770123/job/22198746318?pr=2717: I do not know how I can apply a label to this Pull Request. The label should be `kind/documentation`
- https://github.com/containers/youki/actions/runs/8115770130/job/22198775533?pr=2717: I did not change anything beside the documentation so I do not know how this can fail. Looking at the job log it is unclear to me what is failing, mabe it is this line "Running process_rlimits/process_rlimits.t" but I cannot be sure as there are no "success" message.

**Review by YJDoc2 — APPROVED** [review]
lgtm

**Comment by YJDoc2** [comment]
Thanks @homersimpsons !

I'll go ahead and merge it, as there are no code changes, and the pending CI checks are for tests etc.

**Pull request merged**
