### PR TITLE
initial progress on supporting OwnedFd

### PR DESCRIPTION
**Pull request by zahash**
related to issue https://github.com/containers/youki/issues/2417

### CODE REVIEW

**Review by utam0k — CHANGES_REQUESTED** [review]
@zahash Please elaborate a bit more 🙏

**Comment by zahash** [comment]
@utam0k Sorry i think i linked the wrong issue. I changed it to the correct one just now.

also, a lot of explanation was done in the issue comments

**Comment by utam0k** [comment]
@zahash Thanks for your update, but it's not enough information to start by reviewing it. Apparently, the title of the PR is wrong.

**Comment by YJDoc2** [comment]
@zahash ping!

**Comment by zahash** [comment]
@utam0k @YJDoc2 

i have changed the title.
the idea is, `OwnedFd` cannot be cloned. so before switching to `OwnedFd`, we have to make sure no cloning is done.
the next step would be to use `OwnedFd` inside sender and reciever instead of `RawFd`

**Comment by utam0k** [comment]
💯 

> the idea is, OwnedFd cannot be cloned. so before switching to OwnedFd, we have to make sure no cloning is done.

**Review by utam0k — APPROVED** [review]

**Pull request merged**
