### PR TITLE
[WIP] add rootless option for spec

### PR DESCRIPTION
**Pull request by chenyukang**
Issue: #234

### CODE REVIEW

**Comment by utam0k** [comment]
@chenyukang  Hi! Can I ask you to write out the remaining work?

**Comment by chenyukang** [comment]
> @chenyukang Hi! Can I ask you to write out the remaining work?

Hi @utam0k , I'm busy recently. I will continue with several days later.

**Comment by utam0k** [comment]
I see. I'm looking forward to it. If you want, I'd like to help you.

**Comment by yihuaf** [comment]
> > @chenyukang Hi! Can I ask you to write out the remaining work?
> 
> Hi @utam0k , I'm busy recently. I will continue with several days later.

Keep us posted, and we can pick up after you as well :) No pressure, but do let us know how we can help you.

**Comment by chenyukang** [comment]
> > > @chenyukang Hi! Can I ask you to write out the remaining work?
> > 
> > 
> > Hi @utam0k , I'm busy recently. I will continue with several days later.
> 
> Keep us posted, and we can pick up after you as well :) No pressure, but do let us know how we can help you.

According to [discussion](https://github.com/containers/oci-spec-rs/pull/49), I will have a try to implement add options on youki,
since oci-spec-rs has been updated: https://github.com/containers/youki/pull/303.

I will have a result this week.

**Pull request closed without merging**
