### PR TITLE
Ensure exec command can find config.json

### LINKED ISSUE #584: Using youki and cri-o to run Kubernetes
# Goals

- [ ] Anyway, to be able to create a simple pod
- [ ] Integrate cri-o integration test into youki CI
- [ ] Pass the cri-o integration test.
- [ ] Add the documentation how to run

refs https://github.com/containers/youki/issues/78#issuecomment-999882807

### PR DESCRIPTION
**Pull request by Furisto**
Partially fixes #584. While fixing this I discovered another issue, which I will follow up in the next PR.

### CODE REVIEW

**Comment by utam0k** [comment]
@Furisto I'm sorry, but could you rebase?

**Comment by Furisto** [comment]
@utam0k PTAL

**Comment by utam0k** [comment]
@Furisto Thanks for your PR 😍 
Doesn't this break the exec command? The `config.json` should not be in the bundle directory. I tried the following command and it failed.

```console
$ sudo podman run --name test -it busybox sh
/ 
# and in another console
$ sudo podman exec -it test sh
```

**Comment by Furisto** [comment]
@utam0k The exec command is already broken. This fixes one of the issues (missing config.json), but there is another issue which I alluded to the in the description of this issue which breaks the exec command later on. 

> The `config.json` should not be in the bundle directory.

Unless I am misunderstanding your meaning, it is in the [bundle directory](https://github.com/opencontainers/runtime-spec/blob/main/bundle.md).

**Comment by utam0k** [comment]
> @utam0k The exec command is already broken. This fixes one of the issues (missing config.json), but there is another issue which I alluded to the in the description of this issue which breaks the exec command later on.
> 
> > The `config.json` should not be in the bundle directory.
> 
> Unless I am misunderstanding your meaning, it is in the [bundle directory](https://github.com/opencontainers/runtime-spec/blob/main/bundle.md).

Oh, my local was wrong.

**Review by utam0k — APPROVED** [review]
LGTM

**Pull request merged**
